const PostActionTypes = {
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    NEW_POST: 'NEW_POST',
    EDIT_POST: 'EDIT_POST',
    DELETE_POST: 'DELETE_POST',
};

export default PostActionTypes;