const PostActionTypes = {
    INITIAL_FETCH_POSTS_START: 'INITIAL_FETCH_POSTS_START',
    INITIAL_FETCH_POSTS_SUCCESS: 'INITIAL_FETCH_POSTS_SUCCESS',
    INITIAL_FETCH_POSTS_FAILURE: 'INITIAL_FETCH_POSTS_FAILURE',
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    NEW_POST_START: 'NEW_POST_START',
    NEW_POST_SUCCESS: 'NEW_POST_SUCCESS',
    NEW_POST_FAILURE: 'NEW_POST_FAILURE',
    EDIT_POST: 'EDIT_POST',
    DELETE_POST: 'DELETE_POST',
};

export default PostActionTypes;